--zur aufgabe finden des nächsten Flughafen ist nicht die aufgabe der datenbank
--außerdem warum so viele entitäten einfach nur painfull 

create DATABASE reisebüro;
use reisebüro;



create table kunde(
    kundenNr int unsigned not null primary key AUTO_INCREMENT,
    ort varchar(20),
    postleitzahl varchar(5),
    straße varchar(30),
    Name varchar(20 ) not null

);


create table flug(
    flugdatum date not null,
    listenpreis float not null,
    belegtePlaetze int unsigned not null, 
    flugNr int unsigned not null AUTO_INCREMENT primary key,
    maxPlätze int unsigned not null,
    flugzeugtyp varchar(20) not null, -- oder mit id von letzter aufgabe
    fluggesellschaft varchar(20) not null, 
    Flugziel varchar(30) not null




);

create table buchung(
    buchungsNR int unsigned primary key AUTO_INCREMENT,
    kundenNr int unsigned,
    flugNR int unsigned,
    verkäufer varchar(30) not null, -- oder eigene tabelle mit ids geht jetzt aber über den scope

    foreign key (kundenNr) references kunde(kundenNR),
    foreign key (flugNR) references flug(flugNR)

);

SELECT 
    TABLE_NAME, 
    COLUMN_NAME, 
    COLUMN_TYPE, 
    IS_NULLABLE, 
    COLUMN_KEY, 
    EXTRA
FROM 
    INFORMATION_SCHEMA.COLUMNS
WHERE 
    TABLE_SCHEMA = database()
ORDER BY 
    TABLE_NAME, ORDINAL_POSITION;




-----autogenerated sample data-----
INSERT INTO kunde (ort, postleitzahl, straße, Name)
VALUES 
('Berlin', '10115', 'Friedrichstr. 123', 'Max Mustermann'),
('Muenchen', '80331', 'Marienplatz 5', 'Erika Mueller'),
('Hamburg', '20095', 'Speicherstadt 8', 'John Doe'),
('Frankfurt', '60311', 'Goethe Str. 12', 'Anna Schmidt'),
('Koeln', '50667', 'Hohenstaufenstr. 14', 'Peter Weber');


-- Insert sample data for 'flug' table
INSERT INTO flug (flugdatum, listenpreis, belegtePlaetze, maxPlätze, flugzeugtyp, fluggesellschaft, Flugziel)
VALUES 
('2025-06-01', 350.00, 120, 200, 'Airbus A320', 'Lufthansa', 'New York'),
('2025-06-02', 450.00, 150, 180, 'Boeing 737', 'Ryanair', 'Barcelona'),
('2025-06-03', 300.00, 90, 150, 'Airbus A380', 'Emirates', 'Dubai'),
('2025-06-04', 500.00, 180, 180, 'Boeing 787', 'Qatar Airways', 'Doha'),
('2025-06-05', 600.00, 100, 100, 'Boeing 777', 'Singapore Airlines', 'Singapore');

-- Insert sample data for 'buchung' table
INSERT INTO buchung (kundenNr, flugNR, verkäufer)
VALUES 
(1, 1, 'Sophie Fischer'),
(2, 2, 'Lukas Meyer'),
(3, 3, 'Sarah Klein'),
(4, 4, 'Tom Bauer'),
(5, 5, 'Clara Schmidt');

-----autogenerated sample data end-----


select 
    flugdatum,
    Flugziel,
    (maxPlätze - (select COUNT(*) 
        from buchung 
        where buchung.flugNR = flug.flugNr)) as "verbleibende sitze",
    flugzeugtyp,
    verkäufer

from buchung
join flug on buchung.flugNR = flug.flugNr
join kunde on buchung.kundenNr = kunde.kundenNr
limit 10;


